### ISSUE TITLE
GLRM example throws error

### ISSUE THREAD

**Issue by adityalahiri** [Trusted-AI/AIX360#104]
Hello, 
Iam trying to run [this example notebook for global GLRM explainer](https://github.com/Trusted-AI/AIX360/blob/master/examples/rbm/breast-cancer-logistic.ipynb). I get this error when i execute fit--

ValueError: cannot reindex from a duplicate axis

Any help will be appreciated.
Thanks

**Comment by dennislwei** [comment]
Coincidentally, we just merged PR #103 to fix this issue with pandas. I hope that will fix it for you too.

**Comment by adityalahiri** [comment]
Beautiful. Just saw it and made the changes in file. Works like a charm. Thanks a lot.
