### ISSUE TITLE
ProtoDash for images

### ISSUE THREAD

**Issue by diff7** [Trusted-AI/AIX360#119]
Is it possible to use ProtoDash for images? 

If we use it in an embedding space any recommendations on embedding space?

Thank you in advance.

**Comment by sadhamanus** [comment]
Yes it will work with images as long as the embedding is a vector space. Choice of embedding depends on what you think will work well with euclidean distance for prototype selection. In the code you can change the distance function to some kernel functions such as gaussian etc. but that is not exposed through the interface.

**Comment by diff7** [comment]
Hi, got it. 

Thanks!
