### ISSUE TITLE
Error occurring when running BRCG

### ISSUE THREAD

**Issue by Marleen1** [Trusted-AI/AIX360#123]
I'm trying to run BRCG on some self-generated binary data (note: the generated data is such that there exists a DNF rule that perfectly matches X with y). The first dataset is very small, and looks as follows:

```
X=
   0  1  2  3  4
0  0  1  1  0  0
1  1  0  1  0  0
2  1  1  1  0  0
3  1  1  0  0  1
4  0  1  0  1  0
5  0  1  1  1  0
6  1  0  0  0  1
7  1  1  1  1  1
8  1  0  1  0  1
9  1  0  1  1  0

y=
   0
0  0
1  0
2  0
3  1
4  1
5  1
6  1
7  1
8  1
9  1
```

I then use the following:
```
    br = BooleanRuleCG(lambda0=1e-3, lambda1=1e-3)
    br.fit(Xdf, ydf)
```

The error I get is:

Initial LP solved
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    br.fit(Xdf, ydf)
  File "/home/marleen/miniconda3/envs/aix360_env/lib/python3.7/site-packages/aix360/algorithms/rbm/boolean_rule_cg.py", line 113, in fit
    r[P] = -constraints[0].dual_value
ValueError: shape mismatch: value array of shape (7,) could not be broadcast to indexing result of shape (7,1)

Do you know how to resolve this? Thanks!

**Comment by dennislwei** [comment]
Hi @Marleen1, it looks like `ydf` may be a DataFrame of shape (7, 1) (also guessing from the name). Try making it a Series of shape (7,).

**Comment by Marleen1** [comment]
Ah of course, thanks!
