### ISSUE TITLE
Error from running BRCG in beam_search.py

### ISSUE THREAD

**Issue by Marleen1** [Trusted-AI/AIX360#124]
I'm trying to run BRCG on some self-generated binary data (note: the generated data is such that there exists a DNF rule that perfectly matches X with y). The first dataset is very small, and looks as follows:

```
X=
   0  1  2  3  4
0  0  1  1  0  0
1  1  0  1  0  0
2  1  1  1  0  0
3  1  1  0  0  1
4  0  1  0  1  0
5  0  1  1  1  0
6  1  0  0  0  1
7  1  1  1  1  1
8  1  0  1  0  1
9  1  0  1  1  0

y=
0  0
1  0
2  0
3  1
4  1
5  1
6  1
7  1
8  1
9  1
```
where X is a pandas dataframe and y is a pandas series. I then use the following:

```
    br = BooleanRuleCG(lambda0=1e-3, lambda1=1e-3)
    br.fit(Xdf, ydf)
```
For some datasets this works fine, but for other datasets it gives the following error:

Initial LP solved
Traceback (most recent call last):
  File "dash.py", line 37, in <module>
    br.fit(Xdf, ydf)
  File "/home/marleen/miniconda3/envs/aix360_env/lib/python3.7/site-packages/aix360/algorithms/rbm/boolean_rule_cg.py", line 120, in fit
    K=self.K, UB=UB, D=self.D, B=self.B, eps=self.eps)
  File "/home/marleen/miniconda3/envs/aix360_env/lib/python3.7/site-packages/aix360/algorithms/rbm/beam_search.py", line 284, in beam_search
    colKeep = pd.Series(Xp.columns.get_level_values(0) != i[0], index=Xp.columns)
IndexError: invalid index to scalar variable.

Any idea what is going wrong?

**Comment by dennislwei** [comment]
Did you run [`FeatureBinarizer`](https://github.com/Trusted-AI/AIX360/blob/master/aix360/algorithms/rbm/features.py#L13) on `X`? Even though your `X` is already binary, that might be the problem since `FeatureBinarizer` returns a MultiIndex as the column labels and BRCG expects data in that format.

**Comment by Marleen1** [comment]
Thanks Dennis, yes, using the FeatureBinarizer first solves the issue.
