### ISSUE TITLE
Runtime limit

### ISSUE THREAD

**Issue by Marleen1** [Trusted-AI/AIX360#125]
Hi,

Is it possible to set a maximum runtime for BooleanRuleCG?

**Comment by dennislwei** [comment]
Not currently. The closest is the parameter `iterMax`, which controls the maximum number of (column generation) iterations. 

If you're willing to implement and contribute a runtime limit for BooleanRuleCG, we would be most grateful.

**Comment by dennislwei** [comment]
Addressed by #128. Thanks!
