### ISSUE TITLE
Defect FeatureBinarizer

### ISSUE THREAD

**Issue by HagenVoelzerIBM** [Trusted-AI/AIX360#142]
FeatureBinarizer  in aix360.algorithms.rbm treats binary features (features with only two values) separately. This results in MultiIndex Column names of the binarized data frame being unreadable, and consequently rule predicates used by consumers such as BRCGExplainer, BooleanRuleCG, GLRMExplainer (also in aix360.algorithms.rbm) also being unreadable.

For example, a feature "Gender" with values "F" and "M" is transformed by FeatureBinarizer into the two MultiIndex columns "(Gender, , )" and "(Gender, not, )" rather than "(Gender, ==, F)"  and  "(Gender, ==, M)".

**Comment by dennislwei** [comment]
@HagenVoelzerIBM thanks for raising this issue. I made the smallest change I could come up with to address it. Would appreciate your taking a look at #143.
