### ISSUE TITLE
ModuleNotFoundError: No module named 'aix360.algorithms.rule_induction'

### ISSUE THREAD

**Issue by xiaohan2012** [Trusted-AI/AIX360#163]
Hi,

I tried to run an example notebook via Docker.

I followed the instructions to build the Docker image and run the Jupyter server [here](https://github.com/Trusted-AI/AIX360/#running-in-docker)

However, when I run the notebook [examples/rule_induction/brcg_demo.ipynb](https://github.com/Trusted-AI/AIX360/blob/master/examples/rule_induction/brcg_demo.ipynb)

Importing the dependent libs simply gave:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-33e99aef874b> in <module>
      3 from sklearn.model_selection import train_test_split
      4 from sklearn.metrics import precision_score, recall_score, accuracy_score, balanced_accuracy_score
----> 5 from aix360.algorithms.rule_induction.rbm.boolean_rule_cg import BooleanRuleCG as BRCG
      6 from aix360.algorithms.rbm import FeatureBinarizer
      7 import time

ModuleNotFoundError: No module named 'aix360.algorithms.rule_induction'
```

**Comment by GhadaElkhawaga** [comment]
I get the same error

**Comment by alonbrutzkus** [comment]
I changed the import to:

from aix360.algorithms.rbm import BooleanRuleCG as brcg

This worked for me.

**Comment by xiaohan2012** [comment]
@alonbrutzkus thanks, it worked for me.
