### ISSUE TITLE
aix360.mybluemix.net

### ISSUE THREAD

**Issue by SKYzLine0401** [Trusted-AI/AIX360#190]
Hi!

I want to open the website aix360.mybluemix.net, but I encountered the issue of "404 Not Found: Requested route ('aix360.mybluemix.net') does not exist." How can I resolve this problem?

**Comment by dennislwei** [comment]
Hi @SKYzLine0401, the new website is https://aix360.res.ibm.com/.

**Comment by SKYzLine0401** [comment]
Thank you for your response, I will close this issue.
