### ISSUE TITLE
beam_search_K1 with pandas > 1.1.0

### ISSUE THREAD

**Issue by Hugomiralles** [Trusted-AI/AIX360#97]
With pandas version > 1.1.0, the line 148 (145, and 150) return an error: ValueError: cannot reindex from a duplicate axis.
Locally, locally I just added '.values'. Example of line 148:
`colKeep[i[0]] = ((Xp[i[0]].columns.get_level_values(0) == '<=') & (thresh > i[2])).values`

**Comment by dennislwei** [comment]
@Hugomiralles Thanks a lot for catching this. I think your fix is fine. Would you be so kind as to submit a pull request with the fix?

**Comment by Hugomiralles** [comment]
I can but I am not sure of how to do it properly. Should I only commit with a message explaining the pull request and send it using "git pull origin master"?
For now, I am finishing my internship and master's thesis so I don't have a lot of time but I have a few pull request to do on AIX360 and AIF360.

**Comment by dennislwei** [comment]
No worries. Whenever you do have time, I recommend committing your changes to your own branch or fork of this repository. Then go to the ["Pull requests" tab](https://github.com/Trusted-AI/AIX360/pulls), click "New pull request", and fill it out. We can proceed from there.

Another user just informed me that he encountered a similar issue so he might be able to work on it too.

**Comment by dennislwei** [comment]
@Hugomiralles I got around to fixing the pandas issue in #103 and the tests now pass. Thanks again for bringing this up.

**Comment by Hugomiralles** [comment]
Thanks to you for fixing the issue, I only discover it. Unfortunately, I
did not have the time to do it this month.

Le mar. 29 sept. 2020 à 18:44, dennislwei <notifications@github.com> a
écrit :
